@echo off
REM "ui" extension specification is required
REM because the .py file generated by designer.exe
REM contains 'u' prefix before the target string.
REM In this case, pyside6-lupdate ignores the
REM target. So we must include "ui" extension
REM when executing pyside6-lupdate that contains
REM the original context and target string same as
REM the generated .py file. The lookup key of the
REM translated string seems to be the combination
REM of the context and target string, so there are
REM no reason to consider the inconsistent target
REM string location between .ui and .py.

REM If make .ts file target-wise (to make the
REM translation easy), list up target files and
REM run pyside6-lupdate multiple times.

uv run pyside6-lupdate ^
  -source-language ja_jp ^
  -target-language en_us ^
  -extensions py,ui ^
  pyfemtet_opt_gui ^
  -ts pyfemtet_opt_gui/app_en_us.ts
